'use strict';
const { DataTypes, Op } = require('sequelize');

/**
 * @swagger
 * components:
 *  schemas:
 *      items:
 *          type: object
 *          required:
 *              - code
 *              - active
 *              - name
 *          properties:
 *              id:
 *                  type: integer
 *              code:
 *                  type: string
 *                  description: item code. (~ autogenerated)
 *                  length: 24
 *                  example: ~
 *              eCode:
 *                  type: string
 *                  description: item code. (~ autogenerated)
 *                  length: 24
 *                  example: AD0012
 *                  requreid: false
 *              active:
 *                  type: boolean
 *                  example: true
 *                  default: true
 *              eActive:
 *                  type: boolean
 *              cardType:
 *                  type: integer
 *                  description:
 *                  example: 1
 *              name:
 *                  type: string
 *              name2:
 *                  type: string
 *                  requreid: false
 *              name3:
 *                  type: string
 *                  requreid: false
 *              name4:
 *                  type: string
 *                  requreid: false
 *              specode1:
 *                  type: string
 *                  requreid: false
 *
 *              specode2:
 *                  type: string
 *                  requreid: false
 *              specode3:
 *                  type: string
 *                  requreid: false
 *              specode4:
 *                  type: string
 *                  requreid: false
 *              specode5:
 *                  type: string
 *                  requreid: false
 *              keyword1:
 *                  type: string
 *                  requreid: false
 *              keyword2:
 *                  type: string
 *                  requreid: false
 *              keyword3:
 *                  type: string
 *                  requreid: false
 *              keyword4:
 *                  type: string
 *                  requreid: false
 *              keyword5:
 *                  type: string
 *                  requreid: false
 *              origin:
 *                  type: string
 *                  requreid: false
 *              category:
 *                  type: string
 *                  requreid: false
 *              mainUnit:
 *                  type: string
 *              mainUnitId:
 *                  type: integer
 *                  requreid: false
 *              brandId:
 *                  type: integer
 *              variationCode:
 *                  type: string
 *              reyonCode:
 *                  type: string
 *              producerCode:
 *                  type: string
 *              salesLimitQuantity:
 *                  type: number
 *              status:
 *                  type: string
 */
module.exports = (sequelize) => {
    sequelize.define(
        'items',
        {
            id: {
                type: DataTypes.INTEGER,
                primaryKey: true,
                // autoIncrement: true,
            },
            code: DataTypes.STRING,
            eCode: DataTypes.STRING,
            active: DataTypes.BOOLEAN,
            eActive: DataTypes.BOOLEAN,
            cardType: DataTypes.SMALLINT,
            name: DataTypes.STRING,
            name2: DataTypes.STRING,
            name3: DataTypes.STRING,
            name4: DataTypes.STRING,
            specode1: DataTypes.STRING,
            specode2: DataTypes.STRING,
            specode3: DataTypes.STRING,
            specode4: DataTypes.STRING,
            specode5: DataTypes.STRING,
            keyword1: DataTypes.STRING,
            keyword2: DataTypes.STRING,
            keyword3: DataTypes.STRING,
            keyword4: DataTypes.STRING,
            keyword5: DataTypes.STRING,
            origin: DataTypes.STRING,
            category: DataTypes.STRING,
            mainUnit: DataTypes.STRING,
            mainUnitId: DataTypes.INTEGER,
            brandId: {
                type: DataTypes.INTEGER,
                allowNull: true,
            },
            variationCode: DataTypes.STRING,
            reyonCode: DataTypes.STRING,
            producerCode: DataTypes.STRING,
            salesLimitQuantity: DataTypes.FLOAT,
            status: {
                type: DataTypes.VIRTUAL,
                get() {
                    if (this.eActive && this.active) {
                        return 'active';
                    } else {
                        return 'passive';
                    }
                },
            },
        },
        {
            sequelize,
            tableName: 'AGO_ITEMS',
            scopes: {
                active: {
                    where: {
                        [Op.and]: {
                            active: true,
                            eActive: true,
                        },
                    },
                },
                passive: {
                    where: {
                        [Op.or]: [
                            {
                                active: false,
                            },
                            {
                                eActive: false,
                            },
                        ],
                    },
                },
            },
        }
    );
};
